---
version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: 'github-actions'
    directory: '.github/workflows'
    schedule:
      interval: 'monthly'
    groups:
      github-actions-deps:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'github-actions'
    reviewers:
      - 'Jekwwer'
    assignees:
      - 'Jekwwer'
    commit-message:
      prefix: 'deps(actions)'
    open-pull-requests-limit: 2

  # NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      npm-deps:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'npm'
    reviewers:
      - 'Jekwwer'
    assignees:
      - 'Jekwwer'
    commit-message:
      prefix: 'deps(npm)'
    open-pull-requests-limit: 2

  # Python dependencies
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'monthly'
    versioning-strategy: increase
    groups:
      poetry-deps:
        patterns:
          - '*'
    labels:
      - 'dependencies'
      - 'python'
    reviewers:
      - 'Jekwwer'
    assignees:
      - 'Jekwwer'
    commit-message:
      prefix: 'deps(poetry)'
    open-pull-requests-limit: 2
