# .github/FUNDING.yml:
# Lists funding platforms where Evgenii Shiliaev accepts contributions.
---
github: jekwwer
buy_me_a_coffee: jekwwer
ko_fi: jekwwer
liberapay: jekwwer
open_collective: jekwwer
patreon: jekwwer
# Template by Evgenii Shiliaev - Licensed under CC BY 4.0
# https://github.com/Jekwwer/markdown-docs-kit
# Licensed under: https://github.com/Jekwwer/markdown-docs-kit/blob/main/LICENSE
