---
name: deploy-web-to-github-pages

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: gh-pages-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: checkout-code
        uses: actions/checkout@v6.0.2

      - name: setup-pages
        uses: actions/configure-pages@v6

      - name: upload-pages-artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs

      - name: deploy-to-github-pages
        id: deployment
        uses: actions/deploy-pages@v5
