# .github/workflows/update.yml: Updates the SVG file daily.
---
name: daily-svg-update

on:
  schedule:
    - cron: '0 22 * * *' # Runs daily at 10:00 PM UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4.2.2

      - name: setup-python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.12'

      - name: cache-pip-and-poetry
        uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: install-poetry
        run: pip install poetry

      - name: install-dependencies
        run: poetry install --no-interaction --no-ansi

      - name: generate-updated-svg
        env:
          USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          poetry run python3 update_contributions.py

      - name: commit-updated-svg
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add assets/profile-card-latest.svg assets/profile-card-no-bg-latest.svg
          git commit -m "chore: update contributions stats $(date +'%Y-%m-%d %H:%M:%S')"
          git push
